@startuml

title __MODEL's Class Diagram__\n

  namespace  {
    namespace om.taxapy.viajeservice {
      namespace model {
        class com.taxapy.viajeservice.model.Notification {
            - idUsuario : String
            - latitud : String
            - longitud : String
            {static} - serialVersionUID : long
        }
      }
    }
  }
  

  namespace  {
    namespace om.taxapy.viajeservice {
      namespace model {
        class com.taxapy.viajeservice.model.Taxista {
            - idTaxista : int
            - nombre : String
        }
      }
    }
  }
  

  namespace  {
    namespace om.taxapy.viajeservice {
      namespace model {
        class com.taxapy.viajeservice.model.UserNotification {
            - idTaxista : int
            - nombreTaxista : String
            - placa : String
            {static} - serialVersionUID : long
        }
      }
    }
  }
  

  namespace  {
    namespace om.taxapy.viajeservice {
      namespace model {
        class com.taxapy.viajeservice.model.UsoTaxi {
            - codigo : int
            - fechaUso : String
            - idTaxista : int
            - placa : String
        }
      }
    }
  }
  

  namespace  {
    namespace om.taxapy.viajeservice {
      namespace model {
        class com.taxapy.viajeservice.model.Viaje {
            - codigoViaje : int
            - estado : String
            - fechaViaje : String
            - idTaxista : int
            - idUsuario : String
            - latitud : String
            - longitud : String
            - precio : int
        }
      }
    }
  }
  

  com.taxapy.viajeservice.model.Notification .up.|> Serializable
  com.taxapy.viajeservice.model.UserNotification .up.|> Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
